### ISSUE TITLE
Not enough quorum to forge next block. Will not forge.

### ISSUE THREAD

**Issue by FrancoisCossette** [geopsllc/core-control#113]
Branch: phantom-mainnet

**Describe the bug**
I keep getting an error stating:
```
Detected 1 distinct overheight block 1 header.
Fork 6 - Not enough quorum to forge next block. Will not forge.
```
Sometimes it forges once or twice in a row, then it keeps on missing blocks. I'm kind of new to forging so I might be missing something.

**Expected behavior**
It should forge.

**Logs**
2|phantom-relay  | [2019-12-17 10:26:05][INFO]: Blockchain 100% in sync 💯
1|phantom-forger | [2019-12-17 10:26:10][INFO]: Next forging delegate _USER_ (_ADDRESS_) is active on this node.
2|phantom-relay  | [2019-12-17 10:26:10][INFO]: Block download finished 🚀
2|phantom-relay  | [2019-12-17 10:26:10][INFO]: Blockchain 100% in sync 💯
2|phantom-relay  | [2019-12-17 10:26:16][INFO]: Checking 48 peers 🔭
1|phantom-forger | [2019-12-17 10:26:17][INFO]: Detected 1 distinct overheight block 1 header.
1|phantom-forger | [2019-12-17 10:26:17][INFO]: Fork 6 - Not enough quorum to forge next block. Will not forge.

**System**
Ubuntu 18.04.3 LTS
CPU: 1x Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz with 4 Cores and 4 Threads
Mem: 6.1Gb available
SSD: 40Gb available
core-control: v2.2
phantom-core: v2.2.5

Please help!

**Comment by geopsllc** [comment]
This happens when you node is not actually in sync. The network probably doesn't have enough nodes running at this point and that's why you're seeing that issue.
